import { router } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { usePatients } from '../../context/PatientContext';
import { useLanguage } from '../../context/LanguageContext';

export default function HomeScreen() {
  const { patients } = usePatients();
  const { language, setLanguage, t } = useLanguage();
  return <View style={styles.container}><ScrollView showsVerticalScrollIndicator={false}>
    <View style={styles.header}><View><Text style={styles.greeting}>{t.greeting}</Text><Text style={styles.name}>ASHA Mitra</Text></View><View style={styles.profile}><Text style={styles.profileText}>S</Text></View></View>
    <View style={styles.languageRow}>{['English','हिंदी','मराठी'].map(item => <Pressable key={item} onPress={() => setLanguage(item)} style={[styles.language, language === item && styles.languageSelected]}><Text style={[styles.languageText, language === item && styles.languageTextSelected]}>{item}</Text></Pressable>)}</View>
    <View style={styles.offline}><Text style={styles.offlineDot}>●</Text><Text style={styles.offlineText}>{t.offline} · Cases saved safely on this phone</Text></View>
    <Pressable style={styles.primaryAction} onPress={() => router.push('/screen/CreatePatientScreen')}><View><Text style={styles.primaryEyebrow}>POINT-OF-CARE SCREENING</Text><Text style={styles.primaryTitle}>{t.screen}</Text><Text style={styles.primarySub}>Vitals · symptoms · immediate guidance</Text></View><Text style={styles.primaryArrow}>›</Text></Pressable>
    <Text style={styles.sectionTitle}>Today at a glance</Text>
    <View style={styles.statsRow}><View style={styles.statCard}><Text style={styles.statNumber}>{patients.length}</Text><Text style={styles.statLabel}>{t.patients}</Text></View><View style={[styles.statCard, styles.urgentCard]}><Text style={[styles.statNumber, styles.urgentNumber]}>0</Text><Text style={styles.statLabel}>{t.urgent}</Text></View><View style={styles.statCard}><Text style={styles.statNumber}>2</Text><Text style={styles.statLabel}>{t.due}</Text></View></View>
    <Text style={styles.sectionTitle}>Quick access</Text>
    <View style={styles.actionsRow}><Pressable style={styles.actionCard} onPress={() => router.push('/screen/PatientsScreen')}><Text style={styles.actionIcon}>☷</Text><Text style={styles.actionText}>{t.patients}</Text><Text style={styles.actionHint}>View records & follow-ups</Text></Pressable><Pressable style={styles.actionCard} onPress={() => router.push('/screen/CreatePatientScreen')}><Text style={styles.actionIcon}>＋</Text><Text style={styles.actionText}>Register mother</Text><Text style={styles.actionHint}>New pregnancy record</Text></Pressable></View>
    <Text style={styles.sectionTitle}>Needs attention</Text>
    <View style={styles.attentionCard}><View style={styles.attentionIcon}><Text>↗</Text></View><View style={{flex:1}}><Text style={styles.attentionTitle}>Two follow-ups due today</Text><Text style={styles.attentionText}>Check blood pressure and fetal movement during the visit.</Text></View><Text style={styles.chevron}>›</Text></View>
    <View style={styles.notice}><Text style={styles.noticeTitle}>Clinical safety note</Text><Text style={styles.noticeText}>This tool supports approved assessment and referral. It does not replace clinical judgement or emergency services.</Text></View>
  </ScrollView></View>;
}
const styles = StyleSheet.create({
 container:{flex:1,backgroundColor:'#F8FBFA',paddingHorizontal:20,paddingTop:56},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:18},greeting:{fontSize:14,color:'#64748B'},name:{marginTop:4,fontSize:27,fontWeight:'700',color:'#164A3A'},profile:{width:46,height:46,borderRadius:23,backgroundColor:'#D8F0E7',alignItems:'center',justifyContent:'center'},profileText:{fontSize:19,fontWeight:'700',color:'#16836B'},languageRow:{flexDirection:'row',gap:8,marginBottom:12},language:{paddingVertical:7,paddingHorizontal:11,borderRadius:18,backgroundColor:'#EAF2EF'},languageSelected:{backgroundColor:'#164A3A'},languageText:{color:'#456057',fontSize:12,fontWeight:'700'},languageTextSelected:{color:'#fff'},offline:{flexDirection:'row',alignItems:'center',padding:11,backgroundColor:'#E8F5F0',borderRadius:10},offlineDot:{color:'#16836B',marginRight:7,fontSize:12},offlineText:{color:'#276250',fontSize:12,fontWeight:'600'},primaryAction:{backgroundColor:'#164A3A',borderRadius:20,padding:21,marginTop:17,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},primaryEyebrow:{color:'#A8D8C6',fontSize:10,fontWeight:'800',letterSpacing:1},primaryTitle:{color:'#fff',fontSize:23,fontWeight:'700',marginTop:6},primarySub:{color:'#D9EEE5',fontSize:12,marginTop:6},primaryArrow:{color:'#fff',fontSize:38,fontWeight:'200'},sectionTitle:{fontSize:18,fontWeight:'700',color:'#164A3A',marginBottom:12,marginTop:25},statsRow:{flexDirection:'row',gap:10},statCard:{flex:1,backgroundColor:'#fff',borderRadius:16,padding:14,borderWidth:1,borderColor:'#E5EEEB'},statNumber:{fontSize:25,fontWeight:'700',color:'#16836B'},statLabel:{marginTop:3,fontSize:12,color:'#71827D'},urgentCard:{backgroundColor:'#FFF2EF',borderColor:'#FFD9D1'},urgentNumber:{color:'#C64632'},actionsRow:{flexDirection:'row',gap:12},actionCard:{flex:1,backgroundColor:'#fff',borderRadius:16,padding:16,minHeight:120,justifyContent:'center',borderWidth:1,borderColor:'#E5EEEB'},actionIcon:{fontSize:25,marginBottom:8,color:'#16836B'},actionText:{fontSize:15,fontWeight:'700',color:'#164A3A'},actionHint:{fontSize:11,color:'#71827D',marginTop:5},attentionCard:{backgroundColor:'#FFF8E8',borderRadius:16,padding:16,flexDirection:'row',alignItems:'center',gap:12},attentionIcon:{width:36,height:36,alignItems:'center',justifyContent:'center',backgroundColor:'#FFE5A4',borderRadius:18},attentionTitle:{fontSize:14,fontWeight:'700',color:'#5E4710'},attentionText:{fontSize:12,color:'#7D672B',marginTop:4,lineHeight:17},chevron:{fontSize:25,color:'#8A742F'},notice:{marginTop:20,marginBottom:30,borderLeftWidth:3,borderLeftColor:'#83BDA9',paddingLeft:12},noticeTitle:{color:'#31564A',fontSize:12,fontWeight:'800'},noticeText:{color:'#657B73',fontSize:11,lineHeight:16,marginTop:3}
});
